### ISSUE TITLE
Jobs with external adapters not added to the Market

### ISSUE THREAD

**Issue by bbenligiray** [linkpoolio/market-sync#1]
It should filter Honeycomb jobs out, otherwise partner nodes will not be able to use it as per our service agreement. Our external adapter names start with `honeycomb` for identification.

**Comment by jleeh** [comment]
The tool doesn't upload the job spec unless the user agrees to it being added, it's not fully automated due to the risk of uploading secrets. Even so, it'd also only work if the honeycomb adapters were added to the Market.

**Comment by bbenligiray** [comment]
Thanks, updated the issue title. It may be helpful to clarify that in the readme because I imagine not wanting to add some external adapters or their jobs is a common scenario and in the current state it reads like this application would sync everything automatically.
